### ISSUE TITLE
Deployed stable web app for QA on top of preprod environment

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1738]
### Context: 

- `https://tmail.upn.integration-open-paas.org/`: build on-commit
- `https://tmail.linagora.com/`: Production

no stable platform for QA verify web app before release

### DoD:
- [ ] deployed a QA platform on top of preprod

**Comment by chibenwa** [comment]
Cc @ducnm0711 ?

**Comment by ducnm0711** [comment]
Please discuss with @tk-nguyen about this. We have the deploy on-commit system for dev in LinShare:
https://keel.sh/docs/#harbor-webhooks  
https://keel.sh/docs/#github-webhooks
https://gitlab.com/linagora_private/saas/linshare/linshare-dev-apps/-/blob/main/linshare-6.0-on-commit/values.yaml#L98-100

**Comment by chibenwa** [comment]
It's not on-commit. We already have on-commit

This is a QA environment, duplicate from on-commit (DEV environment).

**Comment by Arsnael** [comment]
I find that description of a task very unclear TBH...

What we have today for tmail-web: 
- on-commit preprod env (`https://tmail.upn.integration-open-paas.org/`)
- prod env based on release (`https://tmail.linagora.com/`)

What we want:
- add an env in our k8s cluster, likely in an other namespace (like we do for tmail-backend with sandbox) based on the release version of tmail-web, so that QA can test on releases before we roll it out on prod :)

**Comment by chibenwa** [comment]
CF https://gitlab.com/linagora_private/saas/devops/devops-backlog/-/issues/225

**Comment by hoangdat** [comment]
this issue completed with https://tmail-qa.upn.integration-open-paas.org/#/? Can we close?
