### ISSUE TITLE
[Composer] [UX] User cannot start writing with the new rows in specific case

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1894]
OS: Android / IOS
Device: Mobile
TMail version: 0.7.9

*Precondition: Turn on the Vietnamese keyboard

### *Reproduce Step:
1, User click on [Compose] button
2, User input "ddddddddddddddd" in to the first row
3, User tap on Enter to go to next row
4, User input "d" immediately

### **Actual:** 
User cannot start writing with new rows. The word will be plus in the first row and it become "dddddddddddddd**đ**"

### **Expected:** 
User can start writing with new rows. We have 2 rows in expectation

### Addition information:
Already compare with other email clients.

https://user-images.githubusercontent.com/124866146/242455576-9d174204-71e4-47d2-9b42-55a0e896d866.mp4

**Comment by QuangHoang1210** [comment]
Still happen on 0.10.4 both android & IOS
-> reopened thís ticket @hoangdat  @dab246 


https://github.com/linagora/tmail-flutter/assets/124866146/88f0cca1-5725-4db6-a7cd-894fe4b29dfa

**Comment by hieutbui** [comment]
@hoangdat While trying to reproduce this problem, i found that it only happens with IOS in 2 case:
- Default IOS keyboard: Always
- Other keyboard (Gkeyboard): Only when recording the screen
### IOS:

https://github.com/linagora/tmail-flutter/assets/80142234/05513001-902c-48ed-8207-c4fc7512336d


### Android:

https://github.com/linagora/tmail-flutter/assets/80142234/083b0857-22e0-4305-ade8-49034ec72990

I though this bug is because the way we handle the break line action in our library: https://github.com/linagora/enough_html_editor.git

**Comment by dab246** [comment]
Fixed at PR #2807

**Comment by QuangHoang1210** [comment]
Passed on IOS version 0.11.3415

https://github.com/linagora/tmail-flutter/assets/124866146/229c6752-b5e5-4be9-9e03-f7f207a02a7a
