### ISSUE TITLE
[CNB] User cannot refresh page when he try it after inactive 10 mins

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2561]
### ENV: 
- Device: IOS
- Browser: SAFARI / CHROME
- ENV: CNB prod

### 19- User trying foward an email but cannot close it after inactive tab for 5 mins

**Step:**
1, User access cnb
2, User login success
3, User switch to home screen or other app / lock screen for 10 mins
4, User refresh the page

**Actual:** 
- cannot refresh
- Loading forever

**Expected:**  
- can refresh page

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/50ed727b-c408-4efa-9602-7ef88183967a)

https://github.com/linagora/tmail-flutter/assets/124866146/f9cdc5c2-bc6f-4c77-a9ea-58a612647543

**Comment by dab246** [comment]
It has not been reproduced yet, further research is needed

**Comment by dab246** [comment]
<img width="853" alt="Screenshot 2024-02-07 at 17 53 27" src="https://github.com/linagora/tmail-flutter/assets/80730648/b1c96934-95c6-4f8d-bc6e-decf5372819a">

According to the console log of this issue. I see this problem is related to not getting the `refresh_token`. And it was fixed at #2508. 

@hoangdat Has that PR commit been released on CNB yet?
@QuangHoang1210 Please test again helps us

**Comment by chibenwa** [comment]
> According to the console log of this issue. I see this problem is related to not getting the refresh_token. And it was fixed at https://github.com/linagora/tmail-flutter/pull/2508.

Supposed to be deployed.
