### ISSUE TITLE
Sort order is fucked up after I move an email out of the INBOX mailbox.

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2586]
![image](https://github.com/linagora/tmail-flutter/assets/6928740/a0cb13ee-d893-4ec4-9778-5d7a815fd9a6)

Sort order is fucked up after I move an email out of the INBOX mailbox.

An analysis showed that the mailbox is sorted after the `Email/get` response and not `Email/query`

Platform: tmail.linagora.com

Regression of https://github.com/linagora/tmail-flutter/pull/2530

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-flutter/assets/6928740/dd3e3f1b-9070-4bca-9456-3c0d76ea4c91

**Comment by chibenwa** [comment]
Reverting commits fails

![image](https://github.com/linagora/tmail-flutter/assets/6928740/9df17056-7db1-41e5-bf69-b0c5607c0518)

**Comment by dab246** [comment]
> sort-order.mp4

It cannot be reproduced.

@chibenwa I have a question, If this is your `Inbox` folder why does it only display a maximum of `14` emails on the screen. Does your `Inbox` currently only have `14` emails?. It's a bit unreasonable because by default we always get at least `20` emails to display for each download.

![Screenshot 2024-02-15 at 11 04 21](https://github.com/linagora/tmail-flutter/assets/80730648/b6af2be8-373d-47f3-9f5a-410d8bdc8b9f)

**Comment by dab246** [comment]
## Propose

- Only sort order by `Email/query` in search mode
- When opening mailbox: Use separate sort order function according to comparator of `sort` property
