### ISSUE TITLE
View PDF should preserve filename

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2737]
### Description

![image](https://github.com/linagora/tmail-flutter/assets/6928740/67cdb6cb-686d-43f6-a871-aa4b444f92b9)

When I click on the attachment to open it in a new tab, and save it: 

![image](https://github.com/linagora/tmail-flutter/assets/6928740/cbb19f19-a21a-4c25-a819-e007f4eaf87f)

The filename is not preserved and I have a super weird UUID instead.

As a user this is annoying, I want the filename to be preserved!

**Comment by tddang-linagora** [comment]
Due to Chrome's limitation, current approach cannot achieve this. More info is discussed in the below threads:
- https://stackoverflow.com/questions/50573429/url-createobjecturlblob-how-do-i-give-a-meaningful-filename-to-a-dynamicall
- https://stackoverflow.com/questions/44061354/set-the-default-save-as-name-for-a-an-embed-or-iframe-that-uses-a-blob
- https://stackoverflow.com/questions/53548182/can-i-set-the-filename-of-a-pdf-object-displayed-in-chrome
- https://stackoverflow.com/questions/41947735/custom-name-for-blob-url

Changing solution direction to `find a js library to display pdf, and try to handle download job (possibly print job also) deliberately`

**Comment by tddang-linagora** [comment]
### Decision
**Different libraries was chosen for each browser below:**
- Firefox: None. It can work by Dart code only.
- Chrome: [PDF.js](https://github.com/mozilla/pdf.js)
- Safari: [PDFObject](https://github.com/pipwerks/pdfobject) (Due to PDF.js bug on Safari - https://github.com/mozilla/pdf.js/issues/17249)

**Comment by hoangdat** [comment]
Use other approach. #2780
