### ISSUE TITLE
If I ask for a read-receipt once for a mail, the option is activated for all my mails

### ISSUE THREAD

**Issue by LNGGlago** [linagora/tmail-flutter#2741]
### Description
When writing a mail, if I ask for a read-receipt, the option is activated for all my mails. I have to go to the parameters to disable it

### Expected result
If I ask the read-receipt for a single mail, the option should not be activated for all my mails. 

#### Reproduction Steps

- Write a new mail
- press the read-receipt button
- go to read-receipt option in parameters, the option is now active

![image](https://github.com/linagora/tmail-flutter/assets/151856136/cb82fd99-2da0-46ba-bd89-c1264003c9dd)

### Context
Chromium, TMail v0.11.3

**Comment by hoangdat** [comment]
Hi Lago, because of the misunderstanding in requirement, we forced turning on the `Always request read reciepts with outgoing messages`. We fixed this, but it has not rolled out. We will roll the patch ASAP. In the meanwhile time, If someone complains about it, let guide him turn it off in `Manage Accounts -> Email read receipts`. 
Thank you.

**Comment by hoangdat** [comment]
fixed in 0.11.4
