### ISSUE TITLE
[Part 2] Refactor New composer

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2919]
### Desc:
- continue work tasks in #2911
- [x] bcc recipients lost after minimize or maximize
- [x] when input many recipients in to/cc/bcc -> web crash
- [x] memory leak when attach files in composer

**Comment by hoangdat** [comment]
@tddang-linagora Can you describe more details which case we have memory leak in attaching files? https://github.com/linagora/tmail-flutter/pull/2911#issuecomment-2157089725

**Comment by tddang-linagora** [comment]
> @tddang-linagora Can you describe more details which case we have memory leak in attaching files? [#2911 (comment)](https://github.com/linagora/tmail-flutter/pull/2911#issuecomment-2157089725)

**Reproducible steps**
- Prepare a heavy, but lower than 20mb, file
- Checkout branch `migrate_dev_to_master_5Jun`
- Run `flutter run -d chrome --web-port 2023 --web-browser-flag "--disable-web-security" --profile`
- Open developer tools (F12) - Memory tab
- Trigger garbage collection then take 1st heap snapshot
- Open composer, pick the prepared file as attachment, wait for upload success
- Delete the composer by tapping on the red trash icon
- Trigger garbage collection then take 2nd heap snapshot, choose compare

**Expected behavior**
There should not be a large different of memory allocation between two snapshots

**Actual behavior**
There is a large memory allocation which is the same size with the attachment inside `system / JSArrayBufferData` section

**Comment by dab246** [comment]
> * [x]  memory leak when attach files in composer

## Reproduce

https://github.com/linagora/tmail-flutter/assets/80730648/577f36bf-05d8-44ad-9e0a-d79b3a2006f4


## Resolved


https://github.com/linagora/tmail-flutter/assets/80730648/e56b77bd-7773-4b3b-b8e6-c0bec698abe8
