### ISSUE TITLE
[PublicAsset][Dev] Handle delete signature

### ISSUE THREAD

**Issue by tddang-linagora** [linagora/tmail-flutter#3043]
## Description
When deleting any identity, we should check if there's any PublicAsset that is unused anywhere else, and do the clean up accordingly

## DoD

- [x] On delete identity, check if that identity contains any PublicAsset. If no, proceed as usual and ignore all steps below.
- [x] Call `PublicAsset/set update` and remove reference of current PublicAsset on this identity
- [x] Proceed to delete identity

**Comment by hoangdat** [comment]
- [ ] handle error for PublicAsset failure

**Comment by tddang-linagora** [comment]
@chibenwa @Arsnael 
If we call `PublicAsset/set destroy` on any PublicAsset, and there were past emails that used it, when user open those emails, they will see that their image inside signature is broken. Is it intended?

**Comment by Arsnael** [comment]
@tddang-linagora very good remark!

Honestly I think the answer for this behavior should be a PO decision. Do we accept that we cleanup public assets once we are sure it's not used anymore and that the image does not shows in signatures for old emails? Or do you think it's acceptable to keep it for such case and never clean them up, as anyways we don't expect this function to be used extensively? But then what happens when we reach the quota? (cause there is a quota^^)

I think because we have a quota mechanism it should be possible to cleanup them, at the possible detriment of some of those images not showing anymore on old messages.

@chibenwa thoughts?

**Comment by chibenwa** [comment]
True. We need to balance opposits:
- keeping images accessible in existing mails
- Not having a cdn for free (prevent abuse)

Thinking about it we can be slightly:
 Only use /set destroy for hard revocation: fir now frontend won't call it.
 We can use a mecanism similar to jmap uploads: up to 200mb quota. If exceeded /set create would delete the oldests public assets without associated identities until it has enough storage, failing if it cannot release enough storage.
That way we have a good compromise between both cobstraints.

Thoughts?

**Comment by Arsnael** [comment]
=> https://github.com/linagora/tmail-backend/issues/1150
