### ISSUE TITLE
[MU] Verify App in Huawei devices

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#3064]
### Desc:
- try to verify tmail app in Huawei devices
- list all components need to change to run app in Huawei

**Comment by dab246** [comment]
## Verified

- Platform: BrowserStack
- Device:  Huawei P30 
- App version: TwakeMail apk build from `sprint_25_flutter_3_22_2` branch
- Feature tested:
   - Login/Logout: **OK**
   - Mailbox/Email list: **OK**
   - Send email: **OK**
   - Mark as read/unread/star: **OK**
   - Move email: **OK**
   - Trash/Spam email: **OK**
   - Search: **OK**
   - Push notification: **FAILED**

## Dead feature

- `Push notification`

## Root Causes

- Huawei phones don’t directly support Firebase due to trade restrictions (`US Trade Restrictions`). Most features on Firebase depend on Google Play Services (GPS). Without GPS on Huawei devices, features like `push notifications`, `real-time database` updates, and `authentication` may not function as seamlessly as they do on other Android devices.

## Workarounds and Alternatives

- `Huawei Mobile Services (HMS)`: Huawei offers its own set of services, including HMS Core, which can replace Firebase features. Integrating HMS Core allows app developers to provide functionalities like push notifications and analytics on Huawei devices. However, this approach works best when you are targeting particular end users.

- `Firebase REST API`: While some Firebase features can be accessed through the Firebase REST API, it requires more development effort. This workaround doesn’t rely on Google Play Services, making it suitable for Huawei devices.

- `Third-Party`: [Superbase](https://supabase.com/)

**Comment by hoangdat** [comment]
Can you more details about information of `P30` devices. Can we test it in newer device? `P60` or `P70`?

**Comment by hoangdat** [comment]
First test in Huawei @guimard @chibenwa

**Comment by dab246** [comment]
> Can you more details about information of `P30` devices. Can we test it in newer device? `P60` or `P70`?

<img width="878" alt="Screenshot 2024-08-06 at 14 36 52" src="https://github.com/user-attachments/assets/60b349d1-3441-4ecd-ae57-c513daf381fa">



BrowserStack currently only has `Huawei P30`. We can search on some other Cloud-Based Testing Services such as
- `Huawei AppGallery Connect`: this needs account verification, I am waiting for Huawei to verify.
- `Firebase Test Lab`: This currently has Huawei Mate 9 device deprecated, need to `submit a request` for a device to be added to the catalog of firebase


> > `authentication` may not function as seamlessly as they do on other Android devices.
> 
> I still not clearly understand on this. Can you more details? @dab246

Generally newer Huawei phones released after May 2019 do not come with GPS pre-installed. So Push notification of Firebase not work on Huawei

**Comment by hoangdat** [comment]
please move forward with `Cloud-Based testing`. Because after 2019, Huawei said that, they dont depend on Android anymore, so we should make sure app still work on these devices (P60, P70, ...)

**Comment by hoangdat** [comment]
Account in AppGallery Connect was rejected. Try to create new one to test.

**Comment by hoangdat** [comment]
Tested in P70 (Cloud testing of Huawei): work well in basic functions


![Image](https://github.com/user-attachments/assets/01a89f99-b49f-452b-a2a4-1b9fda31a15f)
