### ISSUE TITLE
Can not list emails with some configuration in Firefox

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#473]
Report by Fredy Pulido:

```
The error Failed to register/update a ServiceWorker ... Storage .. is caused by this setting:

Delete cookies and site data when Firefox is closed

```

```
I got it working:

DISABLE "Delete cookies and site data when Firefox is closed"
CLEAR DATA for "Your stored cookies, site data, and cache are currently using..."
```

![image](https://user-images.githubusercontent.com/6462404/162358914-6babb132-e6f0-4916-85ae-77095676acea.png)

**Comment by chibenwa** [comment]
If we encounter such an error we can likely refresh everything?

**Comment by hoangdat** [comment]
> If we encounter such an error we can likely refresh everything?

No, I don't think so, but need more investigate

**Comment by dab246** [comment]
I have done:
- Enabled "Delete cookies and site data when Firefox is closed"
- Use Firefox version 100.0.2 (64-bit)
=> As a result it still works fine.


I did:
- Enabled "Clear cookies and site data when Firefox is closed"
- Use Firefox version 100.0.2 (64-bit)
=> As a result it still works fine.

![Screen Shot 2022-05-27 at 16.34.39.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/7d4b62e5-5527-48d5-bd0c-187ec94aa060)

![Screen Shot 2022-05-27 at 16.34.16.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/ba9a8714-afe0-4bca-80e8-f061a098ecb4)

 I suspect this problem is related to `Hive database` and related Firefox version
