### ISSUE TITLE
[Signature] - On the signature panel, the tag "Default" does not display correctly

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#541]
### Description
On the signature panel, the tag "Default" does not display correctly.

### Expected result
On the signature panel, the tag "Default" shoulddisplay correctly.

### Current behaviour
On the signature panel, the tag "Default" does not display correctly.

#### Reproduction Steps
1. Sign in to tmail
2. Account -> Setting
3. Verify the issue

### Context

Pre-production site: https://tmail.upn.integration-open-paas.org/

### Additional information

![image](https://user-images.githubusercontent.com/32490981/167092298-a2c38d67-e292-48db-81e8-2a26bab6d99e.png)

**Comment by hoangdat** [comment]
environment?

**Comment by hoangdat** [comment]
what is `correctly `?

**Comment by Kevinle2312** [comment]
> environment?
Pre-production site: https://tmail.upn.integration-open-paas.org/

**Comment by dab246** [comment]
- This issue has been fixed in this PR [https://github.com/linagora/tmail-flutter/pull/542](https://github.com/linagora/tmail-flutter/pull/542)
- Result 
<img width="1440" alt="Screen Shot 2022-05-06 at 15 26 44" src="https://user-images.githubusercontent.com/80730648/167096132-278f88a2-a0e2-404a-ac64-3fa1f1d11d93.png">
<img width="1440" alt="Screen Shot 2022-05-06 at 15 24 33" src="https://user-images.githubusercontent.com/80730648/167096147-dc986616-7b45-40cb-838d-63f8829ac137.png">

**Comment by Kevinle2312** [comment]
Passed on Pre-production platform
