### ISSUE TITLE
Auto suggestion request too much to back-end

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#692]

**Comment by chibenwa** [comment]
Add a debounce of 1 seconds between auto complete requests

Do not execute outdated auto complete requests

**Comment by chibenwa** [comment]
https://user-images.githubusercontent.com/6928740/176595052-04336fda-d87d-461c-9916-18def011766b.mp4

**Comment by hoangdat** [comment]
IMO, we should use Throttle instead of Debounce.

**Comment by dab246** [comment]
- This problem has been fixed by me in the library project [material_tag_editor](https://github.com/dab246/material_tag_editor.git)
- My improved PR for `material_tag_editor` is here [https://github.com/panuavakul/material_tag_editor/pull/41](https://github.com/panuavakul/material_tag_editor/pull/41)

**Comment by dab246** [comment]
@chibenwa @hoangdat @ManhNTX  Please review it
