### ISSUE TITLE
Sometime composer colors (font + background) are not applied

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#796]
https://user-images.githubusercontent.com/6928740/182508444-d781047a-c9c6-4220-b511-7a1cf841e320.mp4

**Comment by dab246** [comment]
@chibenwa 

- It's not an error. The problem is the way the `html` tag work.  
- You want to change the `color` it can only be changed at the cursor position before you select the new `color`.
- You can watch demo video how it works similar to on `Gmail` and `OpenPaas`

https://user-images.githubusercontent.com/80730648/183567942-0643ce30-e883-4a71-8d6a-02eaafacc45b.mov


https://user-images.githubusercontent.com/80730648/183568048-2daa6203-d361-429d-be5a-add8d2f43072.mov
