### ISSUE TITLE
[iOS] Reset to default color in text color not work

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#875]
https://user-images.githubusercontent.com/6462404/185906315-464d655b-53bb-4de2-ba05-621eb589ab20.MP4

### Expected: 
- Please recheck in Android also

**Comment by haftus98** [comment]
https://images.zenhubusercontent.com/378835363/22847106-7994-470c-8b9d-43dec097b2b1/signal_2022_09_28_113957_002.mp4

I couln't set the text colour

**Comment by dab246** [comment]
@haftus98 

It's not a fault, I think you didn't choose the right color. So the current color is still the default color (black). I think you misunderstood the color picker of this `color picker`.
- If you choose the `wheel` palette. It will have 2 selection circles. The new inner circle is the exact color circle of your choice. Like the demo video, because your screen is small, part of the `color picker` is hidden. You can scroll it down for a fuller view.

![Screen Shot 2022-09-28 at 15.22.25.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/ca4c73cd-d214-4ba4-89a7-31e938ada1f1)


- Also you can choose `Primary` or `Accent` palette for easier use of color picker.

![Screen Shot 2022-09-28 at 15.26.07.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/7fc49f2f-5a06-4d27-8233-b0abc2796b6e)

If you find it difficult to use, don't worry, we will upgrade this `Color Picker` with a new design that will be easier to use in future versions.

**Comment by haftus98** [comment]
verified
