### ISSUE TITLE
unread counter and unread emails show not matched

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#929]
OpenPaaS:

<img width="1786" alt="Screen Shot 2022-09-08 at 10 24 58" src="https://user-images.githubusercontent.com/6462404/189027461-276c5262-cf3f-44c3-ade2-ee1873582c47.png">

TeamMail:

<img width="1791" alt="Screen Shot 2022-09-08 at 10 25 48" src="https://user-images.githubusercontent.com/6462404/189027475-263763ac-483a-4192-9d74-ed14daa4f3c2.png">

@chibenwa @Arsnael Can you check that problem? IMO, it come from back-end site

**Comment by chibenwa** [comment]
Can you retry?

**Comment by hoangdat** [comment]
Still in `openpaas` and `teammail`

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/6462404/189056491-bb1755a7-0165-48c8-9d35-f323cb401268.png">

**Comment by Arsnael** [comment]
Known issue. We have a webadmin task to fix it no? Or is it what you ran @chibenwa but maybe it does not work anymore?

**Comment by Arsnael** [comment]
Actually I double checked... 

I could spot similar issue on my openpaas.linagora.com... 

Then I checked my account on TB... where I could see the missing messages (that I cannot on OpenPaas)
Marked them as read on TB, then the counter cleared out on jmap...

But why they don't appear on openpaas and Tmail? I would likely agree with @hoangdat that there might be some issue in the backend regarding the jmap api. We seem to have many problems with jmap since we switched to BoundedElastic and cass driver 4 so... 

@hoangdat can you confirm that if you look your account in TB you see the missing emails from the counter?

**Comment by hoangdat** [comment]
> can you confirm that if you look your account in TB you see the missing emails from the counter?

yes, via the Mail client in Apple (SMTP/IMAP) every mail are ok

**Comment by Arsnael** [comment]
FYI: https://github.com/linagora/james-project/issues/4612

It might be a tough one to find the cause and fix though so I'm not sure when it will be solved... but thanks for the report!
