### ISSUE TITLE
[Compose mail] email appears twice in "To" field

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#977]
![image](https://user-images.githubusercontent.com/97084773/191958659-6553fce5-f296-4a97-8e63-1c0b8ecb3732.png)

**Current BH**
When entering email, the mail appeared twice

**Expected**
Show once email

**Testing environment**
Chrome /production

**Comment by dab246** [comment]
I checked. This problem is caused by `jmap` returning an `EmailAddress` object consisting of two fields `name` and `email`. The error like the message is because the `name` field contains the content of 2 consecutive `email` addresses as shown.

![Screen Shot 2022-09-27 at 08.58.59.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/d46e2b27-0d81-4e3f-a2a0-9d30c3f38620)

Currently, the display of the email address tag we are dealing with is as follows:
- If `name` is not null, it will display `name` with `avatar`
- If `name` is null will display the `email` address.

In the above scenario, we will see which user's email address is similar to other mail clients.

@hoangdat  WDYT if we just show the `email` field. For me the old script is too good.

**Comment by haftus98** [comment]
![image.png](https://images.zenhubusercontent.com/632aca085051fb7959dab94b/4c418103-2afc-41df-89ec-e6e1b431ae9f)
